Inbox capacity bounding by type
mzabolotko/Kontur pull request #41
Opened 2018-08-05 19:44 UTC by mzabolotko

2018-08-21 22:17 UTC, alexzaitzev requested changes
Please, look at the comments and make changes accordingly.

2018-08-21 22:17 UTC, alexzaitzev commented on .paket/Paket.Restore.targets
> +      <NoWarn>$(NoWarn);NU1603;NU1604;NU1605;NU1608</NoWarn>
Remove it, if it was added unintended

2018-08-21 22:17 UTC, alexzaitzev commented on Kontur.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Kontur.Rabbitmq.IntegrationTests", "Tests\Kontur.Rabbitmq.IntegrationTests\Kontur.Rabbitmq.IntegrationTests.csproj", "{B7886B1F-8577-4CB2-B927-824
Looks like these changes also unintended, better to revert

2018-08-21 22:17 UTC, alexzaitzev commented on .paket/Paket.Restore.targets
> +      <NoWarn>$(NoWarn);NU1603;NU1604;NU1605;NU1608</NoWarn>
Undo these changes, if you not intended to do it.

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur.Rabbitmq/AmqpPublishingBuilder.cs
> +        private readonly AmqpPropertyBuilder propertyBuilder;
Implementation should be under the interfaces

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur.Rabbitmq/AmqpPublishingBuilder.cs
>          public IAmqpConnectionFactory ConnectionFactory { get; private set; }
Private set is redundant

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/Bus.cs
> +        private readonly ConcurrentDictionary<Type, MessageBuffer> inboxes =
It's better for readability to split declaration and initialization.

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/ISubscriptionRegistry.cs
> +        ISubscriptionTag Subscribe<T>(Action<Message<T>> subscriber, int queueCapacity = 1);
In future we should place it into separate class with default value in it

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/MessageDispatcher.cs
> +        ConcurrentDictionary<Type, MessageTargetDictionary> routes =
Property can be made `readonly` and split declaration also

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/MessageDispatcher.cs
> +                else
Redundant else

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/MessageDispatcher.cs
> +            else
Redundant else

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/MessageDispatcher.cs
> +            else
Redundant else

2018-08-21 22:17 UTC, alexzaitzev commented on Sources/Kontur/MessageDispatcherTag.cs
> +    internal class MessageDispatcherTag : IDisposable
Looks that we have too many tags, maybe we can extract interface `Itag` and make only one class `Tag`, for example

2018-08-21 22:17 UTC, alexzaitzev commented on Tests/Kontur.Rabbitmq.Tests/AmqpPublishingBuilderFixture.cs
> +            A.CallTo(() => registry.RegisterPublisher<int>(A<IPublisher>.Ignored)).MustNotHaveHappened();
Trailing spaces at the end of the line

2018-08-21 22:17 UTC, alexzaitzev commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +
Extra new line

2018-08-21 22:17 UTC, alexzaitzev commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +
Extra line

2018-08-21 22:17 UTC, alexzaitzev commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +        public void CanDispatchToSomeSubscribedType()
Name does not reflect what test does

2018-09-02 09:45 UTC, mzabolotko commented on .paket/Paket.Restore.targets
> +      <NoWarn>$(NoWarn);NU1603;NU1604;NU1605;NU1608</NoWarn>
I don't control this file. It updates automatically.

2018-09-02 09:51 UTC, mzabolotko commented on Kontur.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Kontur.Rabbitmq.IntegrationTests", "Tests\Kontur.Rabbitmq.IntegrationTests\Kontur.Rabbitmq.IntegrationTests.csproj", "{B7886B1F-8577-4CB2-B927-824
I have changed the type of the visual studio project to .net core. I think it is O.K.

2018-09-02 09:51 UTC, mzabolotko commented on .paket/Paket.Restore.targets
> +      <NoWarn>$(NoWarn);NU1603;NU1604;NU1605;NU1608</NoWarn>
I don't control this file. It updates automatically.

2018-09-02 10:03 UTC, mzabolotko commented on Sources/Kontur.Rabbitmq/AmqpPublishingBuilder.cs
> +        private readonly AmqpPropertyBuilder propertyBuilder;
Fixed.

2018-09-02 10:04 UTC, mzabolotko commented on Sources/Kontur.Rabbitmq/AmqpPublishingBuilder.cs
>          public IAmqpConnectionFactory ConnectionFactory { get; private set; }
Fixed

2018-09-10 20:10 UTC, mzabolotko commented on Sources/Kontur/MessageDispatcherTag.cs
> +    internal class MessageDispatcherTag : IDisposable
https://github.com/mzabolotko/Kontur/issues/47

2018-09-10 20:12 UTC, mzabolotko commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +
Fixed.

2018-09-10 20:12 UTC, mzabolotko commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +
Fixed.

2018-09-10 20:14 UTC, mzabolotko commented on Tests/Kontur.Rabbitmq.Tests/AmqpPublishingBuilderFixture.cs
> +            A.CallTo(() => registry.RegisterPublisher<int>(A<IPublisher>.Ignored)).MustNotHaveHappened();
Fixed.

2018-09-10 20:26 UTC, mzabolotko commented on Tests/Kontur.Tests/MessageDispatcherFixture.cs
> +        public void CanDispatchToSomeSubscribedType()
Fixed.

2018-09-10 20:30 UTC, mzabolotko commented on Sources/Kontur/Bus.cs
> +        private readonly ConcurrentDictionary<Type, MessageBuffer> inboxes =
Fixed.

2018-09-10 20:32 UTC, mzabolotko commented on Sources/Kontur/MessageDispatcher.cs
> +        ConcurrentDictionary<Type, MessageTargetDictionary> routes =
Fixed.

2018-09-10 20:33 UTC, mzabolotko commented on Sources/Kontur/MessageDispatcher.cs
> +                else
Fixed

2018-09-10 20:34 UTC, mzabolotko commented on Sources/Kontur/MessageDispatcher.cs
> +            else
Fixed

2018-09-10 20:36 UTC, mzabolotko commented on Sources/Kontur/ISubscriptionRegistry.cs
> +        ISubscriptionTag Subscribe<T>(Action<Message<T>> subscriber, int queueCapacity = 1);
O.K.

2018-09-15 23:52 UTC, alexzaitzev approved these changes
LGFM

2018-09-15 23:52 UTC, merged